name: Example Action

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Set Date
        run: echo "DATE=$(date "+%m/%d/%Y")" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Generate new discussion
        id: create-discussion
        uses: benbalter/create-discussion@fetch-repo-id-and-category-id
        with:
          title: "New Discussion ${{ env.DATE }} in General"
          body: |
            Let's Discuss!

      - name: Generate new discussion using file
        id: create-discussion-with-file
        uses: benbalter/create-discussion@use-actions-toolkit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
        with:
          title: "New Discussion ${{ env.DATE }} in General"
          body-filepath: 'zen.txt'
          repository-name: benbalter/create-discussion
          category-name: General      
